### ISSUE TITLE
When syncing dir, all files are selected and stored for random playback, including non media related files

### ISSUE THREAD

**Issue by dot1q** [dot1q/dumbDiscordBot#1]
![image](https://user-images.githubusercontent.com/6827774/32695205-6818c6ca-c71a-11e7-8881-d3f85959de23.png)

Please do the neeful

**Comment by ConnorHollis** [comment]
In generateSoundFileList I think you could use the filter method with a regex match on wav and mp3 before calling map.

```
const generateSoundFileList = (dir) => {
    return fs.readdirSync(dir)
    .filter(file => {
        return path.extname(file).match("^(\.(wav|mp3))$")
    })
    .map(file => {
        return path.join(dir, file);
    });
  };
```

I'll create a PR tomorrow night.

**Comment by dot1q** [comment]
Closing issue, appears to be fixed in latest release, thanks @ConnorHollis.
