### ISSUE TITLE
!TOPWORDS is case sensitive and !TOPWORDS won't work.

### ISSUE THREAD

**Issue by ConnorHollis** [dot1q/dumbDiscordBot#17]
This is a pretty big bug because a lot of the time I have caps lock on and I can't press caps lock again cause my pinkie hurts from playing too many video games.  Please fix th
![hugetopwordsbug](https://user-images.githubusercontent.com/8634028/34471353-297d9d00-eefc-11e7-8a4d-ed78424d429e.png)
is.

**Comment by dot1q** [comment]
Will be available in initial release.
