### ISSUE TITLE
The "gotem" command doesn't work when using google chat

### ISSUE THREAD

**Issue by ConnorHollis** [dot1q/dumbDiscordBot#20]
When using google chat with Greg if you type "gotem" no sound plays. Of course when in discord it does work correctly. Someone should look into th

![image](https://user-images.githubusercontent.com/8634028/35647660-15a0801a-0688-11e8-873d-0a5d48b6d185.png)

is?

**Comment by ConnorHollis** [comment]
This might be user error. I typed gotem as GOTEM which might not be supported.

**Comment by ConnorHollis** [comment]
Not user error, I tried lowercase gotem and it still didn't work...

![image](https://user-images.githubusercontent.com/8634028/35647726-4de91fae-0688-11e8-8968-63a4f4f82a67.png)

**Comment by dot1q** [comment]
Cannot recreate, closing

**Comment by ConnorHollis** [comment]
reopen please

**Comment by ConnorHollis** [comment]
# **GREG PLEASE REPOEN**
