### ISSUE TITLE
Features for !meme function

### ISSUE THREAD

**Issue by dot1q** [dot1q/dumbDiscordBot#28]
Per @ConnorHollis 

1) Upper limit to word count
2) re-roll functionality
3) embed links to original quotes
4) !favorite functionality, highest voted content is placed in a top10 list
5) use words in quote as search for meme template

**Comment by ConnorHollis** [comment]
Please close and open as 5 separate tasks...

**Comment by ConnorHollis** [comment]
Honestly that I even _have_ to tell you this is **embarassing**

**Comment by dot1q** [comment]
Closing, opened as separate issues.
