### ISSUE TITLE
Bot uses incorrect grammar when notifying users of requirements for executing commands.

### ISSUE THREAD

**Issue by ConnorHollis** [dot1q/dumbDiscordBot#3]
Steps to repro:
1) Exit voice channel
2) Type any command
3) Bot types:  "Dude, you need to be in a voice channel to here me!"

It should be "Dude, you need to be in a voice channel to hear me!"

![discordbotissue](https://user-images.githubusercontent.com/8634028/32705343-025bff6a-c7c8-11e7-9bc5-64bd240dd9db.png)
[dnd.txt](https://github.com/dot1q/dumbDiscordBot/files/1465263/dnd.txt)

**Comment by dot1q** [comment]
Fixed in PR #4
